inputcapture: Fix build error due to missing Optional
$ cargo build --all-targets --features=input_capture
   Compiling ashpd v0.13.0-alpha (/path/to/ashpd/client)
error[E0433]: failed to resolve: use of undeclared type `Optional`
   --> client/src/desktop/input_capture.rs:596:26
    |
596 |         let identifier = Optional::from(identifier);
    |                          ^^^^^^^^ use of undeclared type `Optional`

Fixes: 3c47378cab78 ("client: Use Optional for WindowIdentifier")