clipboard: Fix build errors caused by new serialization
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `as_value`
  --> client/src/desktop/clipboard.rs:19:20
   |
19 |     #[serde(with = "as_value", skip_serializing_if = "Vec::is_empty")]
   |                    ^^^^^^^^^^ use of unresolved module or unlinked crate `as_value`

error[E0308]: mismatched types
  --> client/src/desktop/clipboard.rs:15:23
   |
15 | #[derive(Debug, Type, Serialize)]
   |                       ^^^^^^^^^ expected `&Vec<_, _>`, found `&&[&str]`
...
19 |     #[serde(with = "as_value", skip_serializing_if = "Vec::is_empty")]
   |                                                      --------------- arguments to this function are incorrect

Fixes: ec8af6ed589d ("Get rid of SerializeDict/DeserializeDict usages")